Use gradle-serviceloader plugin
Gradle now needs to generate serviceloader entries like Maven does, so
add and configure the gradle-serviceloader plugin where necessary.
Otherwise some of the com.ge.research.sadl.tests will fail and break
the Gradle build.

Tell Travis CI to run Gradle with a single worker to ensure that
Gradle finishes building the jena-wrapper-for-sadl jar before
executing the com.ge.research.sadl.ide:generateXtext task.  Otherwise
my Gradle build was breaking with this exception message,

> java.io.FileNotFoundException: JAR entry com/ge/research/sadl/jena/importer/CsvImporter.class not found in /mnt/c/Users/200003548/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena-wrapper-for-sadl/build/libs/com.ge.research.sadl.jena-wrapper-for-sadl-3.2.0-SNAPSHOT.jar

Also upgrade xtext-gradle-plugin from 1.0.19 to 2.0.7 to make the
deprecated features incompatible with Gradle 5.0 warnings go away.